### ISSUE TITLE
Ollama minimum version requirements and warning

### ISSUE THREAD

**Issue by jamescho72** [redhat-developer/vscode-granite#117] opened 2024-10-29 02:52 UTC
Granite gen3 models requires minimum ollama version 0.3.14

During install confirm ollama version and provide warning and exit out.
Customer expected to upgrade ollama and restart installer.

**Comment by fbricon** [comment] 2024-10-30 16:13
Closing as duplicate of #101

**Closed by fbricon** 2024-10-30 16:13 UTC
Labels: bug
