### ISSUE TITLE
Do not override user's existing settings

### ISSUE THREAD

**Issue by jamescho72** [redhat-developer/vscode-granite#54] opened 2024-09-29 21:35 UTC
We should discuss this on a Monday team meeting.
When they run our extension I assume it will set granite as default for code completion and chat.
We will also have some tunables as part of our model tuning.
But do we want to preserve all other settings that are not related to our granite model?

**Comment by fbricon** [comment] 2024-10-01 14:36
duplicate of #9

**Closed by fbricon** 2024-10-01 14:36 UTC
